### ISSUE TITLE
ProductCard is broken and have problem with its test file

### ISSUE THREAD

**Issue by godon019** [whatssub/whatssub-mobile#75]
with upstream/master ProductCard doesn't render properly

### Expected : 
https://github.com/whatssub/whatssub-mobile/pull/40

### Actual Error: 
![image](https://user-images.githubusercontent.com/10363850/62677634-fe829500-b9e9-11e9-944d-815c2e28a4fd.png)

> I assume the main reason why it is broken is related to `Date()`. but I want to make an issue with another problem here.

### Description:
Normally if the rendering is broken, the Circle-CI produces error when it is running `yarn test` so we could be notified that it is broken 
But Circle-CI didn't know it is broken until someone manually check on it. so it has been passing the test

I assume these written below are where it's gone wrong

First, see `ProductCard.test.tsx.snapshot`
![image](https://user-images.githubusercontent.com/10363850/62677903-d3e50c00-b9ea-11e9-981f-2dca978c288c.png)
it says it is `null`. but it shouldn't be `null` and render components successfully like other snapshot tests

and when it is `null` it shouldn't pass the test. because it is a inappropriate rendering of ProductCard component

But why did it pass? because whether the rendering is broken or not, it is always returning `null` so it passes the test

Secondly, we can see the code here at `Product.test.tsx`
```
  it('should render outer component and snapshot matches', () => {
    act(() => {
      rendered = renderer.create(component()).toJSON();
    });
    expect(rendered).toMatchSnapshot();
  });
```
here `expect(rendered).toBeTruthy();` need to be added so that it makes sure that rendered component is not `null`

therefore, it should be like below
```
  it('should render outer component and snapshot matches', () => {
    act(() => {
      rendered = renderer.create(component()).toJSON();
    });
    expect(rendered).toMatchSnapshot();
    expect(rendered).toBeTruthy();
  });
```
Then the Circle-CI will notify error correctly and not pass the test when it is `null`

Lastly, the reason it is rendering `null` is because it didn't pass proper props to its `ProductCard`. in a `ProductCard.test.tsx` file

```
// props of ProductCard 
interface Props {
  onClickNotification: () => void;
  onClickSubscription?: () => void;
  onClickEdit: () => void;
  isNotificationEnable: boolean;
  isSubscribing?: boolean;
  name: string;
  image: string;
  price: number;
  currentMonthPaymentDate: Date;
  variant?: Variant;
  defaultIsSummary?: boolean;
}
```
> these are not provided

**Comment by godon019** [comment]
@YongPilMoon I hope you can fix this!

**Comment by YongPilMoon** [comment]
@godon019 Thank you for finding the error.  I made pull request to fix it. #80
